### ISSUE TITLE
Nomination of Richard Shea for 'Additional Committee Member'

### ISSUE THREAD

**Issue by shearichard** [nzpug/AGM2016#1]
I nominate myself, Richard Shea, for one of the 'Additional Committee Member' positions.

For some years now I have acted as NZPUG Treasurer - a position I am resigning this year. I would however like to continue to help run NZPUG as a committee member.

I have two particular areas of interest I would like to get involved in from within the committee. These are 
- Encourage and facilitate the videoing of a selection of talks delivered at NZPUG meetups and so provide a means for remote members to enjoy and learn from them
- Promote NZPUG's role in assisting New Zealand teachers in using Python within the curriculum in whatever way is most useful to the teachers.

**Comment by jenofdoom** [comment]
Seconded

**Comment by dannyadair** [comment]
Richard Shea was elected "Additional Committee Member" at the AGM, 11 Sep 2016.
