### ISSUE TITLE
Eric Light for Additional Committee Member

### ISSUE THREAD

**Issue by rhyven** [nzpug/AGM2016#3]
I nominate myself, Eric Light, for one of the 'Additional Committee Member' positions.

I'm the newest member on the committee, and I'm only just finding my feet in our amazing group.  Even in this brief time I've seen the incredible work of the committee, from the new Charitable status, the smooth organisation of Kiwi PyCon, and all the less-obvious work that happens behind the scenes.  

I haven't been engaged in software development for a few years now, but I'm still wildly passionate about Python.  I am a strong advocate for the use of Python within both business and education, and it is this advocacy that I'm most interested in pursuing as a committee member.

I'd like the opportunity this year to extend my efforts on the NZPUG through to 2017, and I'd appreciate your support!  :)

**Comment by jenofdoom** [comment]
Seconded

**Comment by dannyadair** [comment]
Eric Light was not elected "Additional Committee Member" at the AGM, 11 Sep 2016.
