### ISSUE TITLE
Nomination of Danny Adair for 'President'

### ISSUE THREAD

**Issue by dannyadair** [nzpug/AGM2016#4]
I nominate myself, Danny Adair, for the 'President' position.

I've been NZPUG's president since its founding in 2009.
We've come a long way and we still have lots to achieve.
Happy to carry on with my contribution if you want me to :-)

**Comment by jenofdoom** [comment]
Seconded

**Comment by dannyadair** [comment]
Danny Adair was elected "President" at the AGM, 11 Sep 2016.
