### ISSUE TITLE
Nomination of Tom Eastman for Vice President

### ISSUE THREAD

**Issue by jenofdoom** [nzpug/AGM2016#5]
With Tom's continued involvement in the Python community both here in NZ and as an international speaker, and his successful directorship of Kiwi PyCon 2014, I think he would make an excellent Vice President, and so I nominate him for that.

**Comment by rhyven** [comment]
Seconded

**Comment by dannyadair** [comment]
Tom Eastman was elected "Vice President" at the AGM, 11 Sep 2016.
